config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "users/:id/follow" => "users#follow", as: "follow"
  get "users/:id/follower" => "users#follower", as: "follower"
  devise_for :users
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update,:follow,:follower] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :book_comments, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  # def self.week_count
  #   Book.joins(:favorites).where(favorites: { created_at: 0.days.ago.prev_week..0.days.ago.prev_week(:sunday)}).group(:id).order("count(*) desc")
  # end

def self.looks(search, word)
  if search == "perfect_match"
    @book = Book.where("title LIKE?", "#{word}")
  elsif search == "forward_match"
    @book = Book.where("title LIKE?", "#{word}%")
  elsif search == "backward_match"
    @book = Book.where("title LIKE?", "%#{word}")
  elsif search == "partical_match"
    @book = Book.where("title LIKE?", "%#{word}%")
  else
    @book = Book.all
  end
end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :is_matching_login_user, only: [:edit, :update, :destroy]


  def index
    @books = Book.includes(:favorited_users).sort{|a,b| b.favorited_users.size <=> a.favorited_users.size}
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    @user = Book.find(params[:id])
    user_id = @user.user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to books_path
    end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
            <div>
              <% book.book_comments.each do |book_comment| %>
                <%= image_tag book_comment.user.get_profile_image, size:"50x50" %>
                <%= book_comment.comment %>
                <% if book_comment.user == current_user %>
                  <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment),local: false,remote: true, method: :delete, class: "btn btn-danger" %>
                <% end %>
                <p><%= link_to book_comment.user.name, user_path(book_comment.user_id) %></p>
              <% end %>
            </div>
            <div>
              <%= form_with(model:[book, book_comment],local: false,remote: true) do |f| %>
                <%= f.text_area :comment, rows:'6' ,cols:'60', placeholder: "comment is here" %>
                <p><%= f.submit "送信" %></p>
              <% end %>
            </div>

app/views/books/_count.html.erb
コメント数:<%= book.book_comments.count %>

app/views/books/_favorite.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete do %>
    ♥<%= book.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :create do %>
      ♡<%= book.favorites.count %>
    <% end %>
  <% end %>

app/views/books/_form.html.erb
<%= form_with url: books_path,scope: :book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title',value: '' %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control book_body',value: '' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book",class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="favorite_buttons_<%= book.id %>">
          <%= render "favorites/favorite",book: book %>
        </td>
        <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
      <%= form_with model: @book,local:true do |f| %>
      <%= render 'layouts/errors', obj: @book %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book",class: 'btn btn-success' %>
        </div>
      <% end %>
      		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'layouts/errors', obj: @book%>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"70x70" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td id="favorite_buttons_<%= @book.id %>">
            <%= render 'favorites/favorite', book: @book %>
          </td>
          <td class="comment">
            <%= render 'books/count', book: @book %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
      </table>
        <div class="comment_area">
          <%= render partial: 'books/comment',locals: { book: @book, book_comment: @book_comment} %>
        </div>
      </div>
    </div>
  </div>
</div>